In [1]:
import numpy as np

In [5]:
a = np.array([2,4,6,8])
a_list = [2,4,6,8]

In [6]:
type(a)

numpy.ndarray

In [7]:
type(a_list)

list

In [18]:
print(a/2)

[1. 2. 3. 4.]


In [17]:
print(a_list/2)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [13]:
for i in range(0, len(a_list)):
    a_list[i] = a_list[i]/2

In [14]:
a_list

[1.0, 2.0, 3.0, 4.0]

In [19]:
print(a)

[2 4 6 8]


In [61]:
b = np.array([ [1,2,3], [4,5,6] ])

In [55]:
print(b)

[[1 2 3]
 [4 5 6]]


In [25]:
a[1], a[2]

(4, 6)

In [29]:
b[0][1], b[1][0]

(2, 4)

In [31]:
b[0,1], b[1,0]

(2, 4)

In [32]:
b[0,2]

3

In [33]:
a

array([2, 4, 6, 8])

In [44]:
a = np.append(a, 2)

In [43]:
a = np.append(a, 3)

In [45]:
a

array([2, 4, 6, 8, 3, 2])

In [48]:
a[2:9] #6,8,3,2 | 6,2 | 

array([6, 8, 3, 2])

In [49]:
print(b)

[[1 2 3]
 [4 5 6]]


In [66]:
c = np.array([[1,2,3], [2,3,5], [10,8,6], [4,11,17] ])

In [67]:
c 

array([[ 1,  2,  3],
       [ 2,  3,  5],
       [10,  8,  6],
       [ 4, 11, 17]])

In [68]:
c[:3] #10,8, 6 | [1,2,3], [2,3,5], [10,8,6] |

array([[ 1,  2,  3],
       [ 2,  3,  5],
       [10,  8,  6]])

In [69]:
c[:2, 2] #[1,2,3], [2,3,5] | [3,4] |[3,5]

array([3, 5])

In [74]:
print(c[:2, 2])

[3 5]


In [78]:
d = c.tolist()

In [79]:
d, type(d)

([[1, 2, 3], [2, 3, 5], [10, 8, 6], [4, 11, 17]], list)

In [80]:
d 

[[1, 2, 3], [2, 3, 5], [10, 8, 6], [4, 11, 17]]

In [81]:
d = np.array(d)

In [82]:
d

array([[ 1,  2,  3],
       [ 2,  3,  5],
       [10,  8,  6],
       [ 4, 11, 17]])

In [84]:
d.ndim

2

In [85]:
a = np.array([2,4,6,8])

In [86]:
a.ndim

1

In [87]:
a.size

4

In [88]:
d.size

12

In [89]:
a.shape

(4,)

In [90]:
d.shape

(4, 3)

## Operasi pada Array (Matrix)

In [97]:
print(d,  '\n' , d.shape)

[[ 1  2  3]
 [ 2  3  5]
 [10  8  6]
 [ 4 11 17]] 
 (4, 3)


In [102]:
b = np.array([[10,8,13], [1,4,7], [31,23,10], [1,2,3]])
print(b, b.shape)

[[10  8 13]
 [ 1  4  7]
 [31 23 10]
 [ 1  2  3]] (4, 3)


In [111]:
print(f"{d} \n\n * \n\n {b} =")

[[ 1  2  3]
 [ 2  3  5]
 [10  8  6]
 [ 4 11 17]] 

 * 

 [[10  8 13]
 [ 1  4  7]
 [31 23 10]
 [ 1  2  3]] =


In [105]:
print(d*b)

[[ 10  16  39]
 [  2  12  35]
 [310 184  60]
 [  4  22  51]]


In [116]:
print(b, b.shape)

[[10  8 13]
 [ 1  4  7]
 [31 23 10]
 [ 1  2  3]] (4, 3)


In [123]:
a = np.array([ [1,2], [4,5] ])
print(a, '\n' , a.shape)

[[1 2]
 [4 5]] 
 (2, 2)


In [114]:
print(np.matmul(b,a))

[[133 177]
 [ 66  85]
 [193 267]
 [ 30  39]]


In [119]:
try:
    e = np.matmul(b,a)
    print(e)
except:
    print("Dimensi tidak benar, n!= p")


[[133 177]
 [ 66  85]
 [193 267]
 [ 30  39]]


In [120]:
print('banyaknya entry = ', a.size)
print('dimensi array = ', a.ndim)
print('ukuran array = ', a.shape)

banyaknya entry =  6
dimensi array =  2
ukuran array =  (3, 2)


In [126]:
print("Determinan Matriks a = ", np.linalg.det(a))

Determinan Matriks a =  -2.9999999999999996


In [128]:
print("Invers Matriks a = \n", np.linalg.inv(a))

Invers Matriks a = 
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [130]:
eig_val, eig_vecs = np.linalg.eig(a)

In [141]:
eig_val_1 = eig_val[0]
eig_val_1.real

-0.4641016151377544

In [142]:
eig_vecs

array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]])

In [143]:
np.matmul(a,eig_vecs)

array([[ 0.37448277, -2.22186537],
       [-0.27414041, -6.07024909]])

In [147]:
a

array([[1, 2],
       [4, 5]])

In [131]:
eig_val

array([-0.46410162,  6.46410162])

In [144]:
(eig_val_1 * eig_vecs)

array([[ 0.37448277,  0.15952276],
       [-0.27414041,  0.43582428]])

In [146]:
eig_val[1] * eig_vecs

array([[-5.2158721 , -2.22186537],
       [ 3.81828338, -6.07024909]])